In [3]:
import cv2
import os

def save_video_frames(video_path, output_dir):
    """
    Reads frames from a video file and saves them as images in the specified directory.
    
    Args:
    - video_path (str): Path to the video file.
    - output_dir (str): Directory where frames will be saved.
    """
    # Create the output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)
    
    # Capture the video
    cap = cv2.VideoCapture(video_path)
    frame_count = 0
    
    while True:
        ret, frame = cap.read()
        if not ret:
            break  # Exit the loop if there are no more frames
        
        # Construct the filename for the frame
        frame_filename = os.path.join(output_dir, f"frame_{frame_count:04d}.jpg")
        
        # Save the frame as an image
        cv2.imwrite(frame_filename, frame)
        frame_count += 1
    
    # Release the video capture object
    cap.release()
    print(f"Saved {frame_count} frames to {output_dir}")

# Example usage
if __name__ == "__main__":
    save_video_frames('/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/video 1.mp4', '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/frame_video1')
    save_video_frames('/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/video 2.mp4', '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/frame_video2')

Saved 232 frames to /home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/frame_video1
Saved 392 frames to /home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/frame_video2


In [13]:
import cv2
import pandas as pd
import os
import numpy as np

def load_keypoints_from_csv(file_path):
    """Load keypoints from a CSV file."""
    keypoints = pd.read_csv(file_path).values
    # Reshape the keypoints to (num_frames, num_keypoints, 3)
    num_keypoints = 33  # Assuming there are 33 keypoints
    reshaped_keypoints = keypoints.reshape(-1, num_keypoints, 3)
    return reshaped_keypoints

def visualize_keypoints_and_lines(frames_dir, keypoints1, keypoints2, output_dir):
    """
    Visualize keypoints and connecting lines on each frame and save the results.
    
    Args:
    - frames_dir (str): Directory containing the frames.
    - keypoints1 (np.array): Array of keypoints for video 1.
    - keypoints2 (np.array): Array of keypoints for video 2.
    - output_dir (str): Directory to save the visualized frames.
    """
    os.makedirs(output_dir, exist_ok=True)  # Create output directory if it doesn't exist
    
    frame_files = sorted(os.listdir(frames_dir))  # Get sorted list of frame files
    for i, frame_file in enumerate(frame_files):
        frame_path = os.path.join(frames_dir, frame_file)
        frame = cv2.imread(frame_path)
        
        # Draw keypoints and lines for video 1 (in green)
        for kp in keypoints1[i]:
            x, y, _ = kp  # Unpack the keypoint coordinates
            cv2.circle(frame, (int(x), int(y)), 5, (0, 255, 0), -1)  # Draw a green circle for each keypoint
        
        # Draw lines connecting keypoints for video 1
        for j in range(len(keypoints1[i]) - 1):
            x1, y1, _ = keypoints1[i][j]
            x2, y2, _ = keypoints1[i][j + 1]
            cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0, 255, 0), 2)  # Green lines

        # Draw keypoints and lines for video 2 (in red)
        for kp in keypoints2[i]:
            x, y, _ = kp  # Unpack the keypoint coordinates
            cv2.circle(frame, (int(x), int(y)), 5, (0, 0, 255), -1)  # Draw a red circle for each keypoint
        
        # Draw lines connecting keypoints for video 2
        for j in range(len(keypoints2[i]) - 1):
            x1, y1, _ = keypoints2[i][j]
            x2, y2, _ = keypoints2[i][j + 1]
            cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0, 0, 255), 2)  # Red lines
        
        # Save the visualized frame
        output_path = os.path.join(output_dir, frame_file)
        cv2.imwrite(output_path, frame)

# Example usage
if __name__ == "__main__":
    keypoints1_path = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/video_1_keypoints.csv'
    keypoints2_path = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/video_2_keypoints.csv'
    frames_dir = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/frame_video1'
    output_dir = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/visualized_frames_comparison'
    
    keypoints1 = load_keypoints_from_csv(keypoints1_path)
    keypoints2 = load_keypoints_from_csv(keypoints2_path)

    # Debugging: Check the shape and first few entries of the keypoints
    print(f"Keypoints 1 shape: {keypoints1.shape}, first few entries: {keypoints1[:5]}")
    print(f"Keypoints 2 shape: {keypoints2.shape}, first few entries: {keypoints2[:5]}")
    
    visualize_keypoints_and_lines(frames_dir, keypoints1, keypoints2, output_dir)


Keypoints 1 shape: (47, 33, 3), first few entries: [[[ 6.03300750e-01  5.52692294e-01 -1.95211917e-01]
  [ 6.18618906e-01  5.58323503e-01 -2.22020864e-01]
  [ 6.18251562e-01  5.59756875e-01 -2.22105175e-01]
  [ 6.17795587e-01  5.61484694e-01 -2.22289324e-01]
  [ 6.19659901e-01  5.57525873e-01 -1.74287975e-01]
  [ 6.20069623e-01  5.58295071e-01 -1.74275324e-01]
  [ 6.20448589e-01  5.59215784e-01 -1.74427286e-01]
  [ 6.05643868e-01  5.77201009e-01 -2.94328988e-01]
  [ 6.08766437e-01  5.73164642e-01 -8.65408108e-02]
  [ 5.83181262e-01  5.56742966e-01 -2.18332827e-01]
  [ 5.85695028e-01  5.54754913e-01 -1.57777682e-01]
  [ 4.88459468e-01  5.95741391e-01 -4.00253475e-01]
  [ 4.97685313e-01  5.73144495e-01  6.58904389e-02]
  [ 3.41768056e-01  6.14875138e-01 -4.18926537e-01]
  [ 3.54874223e-01  5.83465278e-01  1.25370622e-01]
  [ 2.09191889e-01  6.17915630e-01 -3.81543338e-01]
  [ 2.42857769e-01  5.92583776e-01  9.21090543e-02]
  [ 1.67278796e-01  6.23061538e-01 -4.36555445e-01]
  [ 2.1766355

IndexError: index 47 is out of bounds for axis 0 with size 47

In [14]:
import cv2
import pandas as pd
import os
import numpy as np

def load_keypoints_from_csv(file_path):
    """Load keypoints from a CSV file."""
    keypoints = pd.read_csv(file_path).values
    print(f"Keypoints data shape: {keypoints.shape}")  # Debug: check shape of the data
    print(f"First few keypoints: {keypoints[:5]}")  # Debug: print first few keypoints to inspect
    
    num_keypoints = 33  # Assuming there are 33 keypoints
    # Reshape the keypoints to (num_frames, num_keypoints, 3)
    reshaped_keypoints = keypoints.reshape(-1, num_keypoints, 3)
    return reshaped_keypoints

def visualize_keypoints_and_lines(frames_dir, keypoints1, keypoints2, output_dir):
    """
    Visualize keypoints and connecting lines on each frame and save the results.
    
    Args:
    - frames_dir (str): Directory containing the frames.
    - keypoints1 (np.array): Array of keypoints for video 1.
    - keypoints2 (np.array): Array of keypoints for video 2.
    - output_dir (str): Directory to save the visualized frames.
    """
    os.makedirs(output_dir, exist_ok=True)  # Create output directory if it doesn't exist
    
    frame_files = sorted(os.listdir(frames_dir))  # Get sorted list of frame files
    for i, frame_file in enumerate(frame_files):
        frame_path = os.path.join(frames_dir, frame_file)
        frame = cv2.imread(frame_path)
        
        # Ensure there is enough data for the frame (i.e., keypoints should exist for this frame)
        if i >= len(keypoints1) or i >= len(keypoints2):
            continue  # Skip if no keypoints for this frame
        
        # Draw keypoints and lines for video 1 (in green)
        for kp in keypoints1[i]:
            x, y, _ = kp  # Unpack the keypoint coordinates
            cv2.circle(frame, (int(x), int(y)), 5, (0, 255, 0), -1)  # Draw a green circle for each keypoint
        
        # Draw lines connecting keypoints for video 1
        for j in range(len(keypoints1[i]) - 1):
            x1, y1, _ = keypoints1[i][j]
            x2, y2, _ = keypoints1[i][j + 1]
            cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0, 255, 0), 2)  # Green lines

        # Draw keypoints and lines for video 2 (in red)
        for kp in keypoints2[i]:
            x, y, _ = kp  # Unpack the keypoint coordinates
            cv2.circle(frame, (int(x), int(y)), 5, (0, 0, 255), -1)  # Draw a red circle for each keypoint
        
        # Draw lines connecting keypoints for video 2
        for j in range(len(keypoints2[i]) - 1):
            x1, y1, _ = keypoints2[i][j]
            x2, y2, _ = keypoints2[i][j + 1]
            cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0, 0, 255), 2)  # Red lines
        
        # Save the visualized frame
        output_path = os.path.join(output_dir, frame_file)
        cv2.imwrite(output_path, frame)

# Example usage
if __name__ == "__main__":
    keypoints1_path = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/video_1_keypoints.csv'
    keypoints2_path = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/video_2_keypoints.csv'
    frames_dir = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/frame_video1'
    frame_dir2 = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/frame_video2'
    output_dir = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/comparision'
    
    keypoints1 = load_keypoints_from_csv(keypoints1_path)
    keypoints2 = load_keypoints_from_csv(keypoints2_path)

    # Debugging: Check the shape and first few entries of the keypoints
    print(f"Keypoints 1 shape: {keypoints1.shape}, first few entries: {keypoints1[:5]}")
    print(f"Keypoints 2 shape: {keypoints2.shape}, first few entries: {keypoints2[:5]}")
    
    visualize_keypoints_and_lines(frames_dir, keypoints1, keypoints2, output_dir)


Keypoints data shape: (47, 99)
First few keypoints: [[ 6.03300750e-01  5.52692294e-01 -1.95211917e-01  6.18618906e-01
   5.58323503e-01 -2.22020864e-01  6.18251562e-01  5.59756875e-01
  -2.22105175e-01  6.17795587e-01  5.61484694e-01 -2.22289324e-01
   6.19659901e-01  5.57525873e-01 -1.74287975e-01  6.20069623e-01
   5.58295071e-01 -1.74275324e-01  6.20448589e-01  5.59215784e-01
  -1.74427286e-01  6.05643868e-01  5.77201009e-01 -2.94328988e-01
   6.08766437e-01  5.73164642e-01 -8.65408108e-02  5.83181262e-01
   5.56742966e-01 -2.18332827e-01  5.85695028e-01  5.54754913e-01
  -1.57777682e-01  4.88459468e-01  5.95741391e-01 -4.00253475e-01
   4.97685313e-01  5.73144495e-01  6.58904389e-02  3.41768056e-01
   6.14875138e-01 -4.18926537e-01  3.54874223e-01  5.83465278e-01
   1.25370622e-01  2.09191889e-01  6.17915630e-01 -3.81543338e-01
   2.42857769e-01  5.92583776e-01  9.21090543e-02  1.67278796e-01
   6.23061538e-01 -4.36555445e-01  2.17663556e-01  5.96810400e-01
   1.00810528e-01  1.616

In [18]:
import cv2
import pandas as pd
import os
import numpy as np

def load_keypoints_from_csv(file_path):
    """Load keypoints from a CSV file."""
    keypoints = pd.read_csv(file_path).values
    print(f"Keypoints data shape: {keypoints.shape}")  # Debug: check shape of the data
    print(f"First few keypoints: {keypoints[:5]}")  # Debug: print first few keypoints to inspect
    
    num_keypoints = 33  # Assuming there are 33 keypoints
    # Reshape the keypoints to (num_frames, num_keypoints, 3)
    reshaped_keypoints = keypoints.reshape(-1, num_keypoints, 3)
    return reshaped_keypoints

def visualize_keypoints_and_lines(frames_dir1, frames_dir2, keypoints1, keypoints2, output_dir):
    """
    Visualize keypoints and connecting lines on each frame from both videos and save the results.
    
    Args:
    - frames_dir1 (str): Directory containing the frames for video 1.
    - frames_dir2 (str): Directory containing the frames for video 2.
    - keypoints1 (np.array): Array of keypoints for video 1.
    - keypoints2 (np.array): Array of keypoints for video 2.
    - output_dir (str): Directory to save the visualized frames.
    """
    os.makedirs(output_dir, exist_ok=True)  # Create output directory if it doesn't exist
    
    frame_files1 = sorted(os.listdir(frames_dir1))  # Get sorted list of frame files for video 1
    frame_files2 = sorted(os.listdir(frames_dir2))  # Get sorted list of frame files for video 2
    
    # Ensure both videos have the same number of frames
    if len(frame_files1) != len(frame_files2):
        print(f"Warning: Frame count mismatch between the two videos: {len(frame_files1)} vs {len(frame_files2)}")
    
    for i in range(min(len(frame_files1), len(frame_files2))):  # Loop through all available frames
        frame_path1 = os.path.join(frames_dir1, frame_files1[i])
        frame_path2 = os.path.join(frames_dir2, frame_files2[i])
        
        frame1 = cv2.imread(frame_path1)
        frame2 = cv2.imread(frame_path2)
        
        # Ensure there is enough data for the frame (i.e., keypoints should exist for this frame)
        if i >= len(keypoints1) or i >= len(keypoints2):
            continue  # Skip if no keypoints for this frame
        
        # Draw keypoints and lines for video 1 (in green) on frame 1
        for kp in keypoints1[i]:
            x, y, _ = kp  # Unpack the keypoint coordinates
            cv2.circle(frame1, (int(x), int(y)), 5, (0, 255, 0), -1)  # Draw a green circle for each keypoint
        
        # Draw lines connecting keypoints for video 1
        for j in range(len(keypoints1[i]) - 1):
            x1, y1, _ = keypoints1[i][j]
            x2, y2, _ = keypoints1[i][j + 1]
            cv2.line(frame1, (int(x1), int(y1)), (int(x2), int(y2)), (0, 255, 0), 2)  # Green lines

        # Draw keypoints and lines for video 2 (in red) on frame 2
        for kp in keypoints2[i]:
            x, y, _ = kp  # Unpack the keypoint coordinates
            cv2.circle(frame2, (int(x), int(y)), 5, (0, 0, 255), -1)  # Draw a red circle for each keypoint
        
        # Draw lines connecting keypoints for video 2
        for j in range(len(keypoints2[i]) - 1):
            x1, y1, _ = keypoints2[i][j]
            x2, y2, _ = keypoints2[i][j + 1]
            cv2.line(frame2, (int(x1), int(y1)), (int(x2), int(y2)), (0, 0, 255), 2)  # Red lines
        
        # Concatenate the two frames horizontally to visualize the comparison
        combined_frame = np.hstack((frame1, frame2))
        
        # Save the visualized frame
        output_path = os.path.join(output_dir, f"frame_{i:04d}.jpg")
        cv2.imwrite(output_path, combined_frame)

# Example usage
if __name__ == "__main__":
    # keypoints1_path = 'path_to_video_1_keypoints.csv'
    # keypoints2_path = 'path_to_video_2_keypoints.csv'
    # frames_dir1 = 'path_to_frames_video1'
    # frames_dir2 = 'path_to_frames_video2'
    # output_dir = 'path_to_output_visualizations'

    keypoints1_path = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/video_1_keypoints.csv'
    keypoints2_path = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/video_2_keypoints.csv'
    frames_dir1 = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/frame_video1'
    frames_dir2 = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/frame_video2'
    output_dir = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/comparision'
    
    
    keypoints1 = load_keypoints_from_csv(keypoints1_path)
    keypoints2 = load_keypoints_from_csv(keypoints2_path)

    # Debugging: Check the shape and first few entries of the keypoints
    print(f"Keypoints 1 shape: {keypoints1.shape}, first few entries: {keypoints1[:5]}")
    print(f"Keypoints 2 shape: {keypoints2.shape}, first few entries: {keypoints2[:5]}")
    
    visualize_keypoints_and_lines(frames_dir1, frames_dir2, keypoints1, keypoints2, output_dir)


Keypoints data shape: (47, 99)
First few keypoints: [[ 6.03300750e-01  5.52692294e-01 -1.95211917e-01  6.18618906e-01
   5.58323503e-01 -2.22020864e-01  6.18251562e-01  5.59756875e-01
  -2.22105175e-01  6.17795587e-01  5.61484694e-01 -2.22289324e-01
   6.19659901e-01  5.57525873e-01 -1.74287975e-01  6.20069623e-01
   5.58295071e-01 -1.74275324e-01  6.20448589e-01  5.59215784e-01
  -1.74427286e-01  6.05643868e-01  5.77201009e-01 -2.94328988e-01
   6.08766437e-01  5.73164642e-01 -8.65408108e-02  5.83181262e-01
   5.56742966e-01 -2.18332827e-01  5.85695028e-01  5.54754913e-01
  -1.57777682e-01  4.88459468e-01  5.95741391e-01 -4.00253475e-01
   4.97685313e-01  5.73144495e-01  6.58904389e-02  3.41768056e-01
   6.14875138e-01 -4.18926537e-01  3.54874223e-01  5.83465278e-01
   1.25370622e-01  2.09191889e-01  6.17915630e-01 -3.81543338e-01
   2.42857769e-01  5.92583776e-01  9.21090543e-02  1.67278796e-01
   6.23061538e-01 -4.36555445e-01  2.17663556e-01  5.96810400e-01
   1.00810528e-01  1.616

In [20]:
import cv2
import pandas as pd
import os
import numpy as np

def load_keypoints_from_csv(file_path):
    """Load keypoints from a CSV file."""
    keypoints = pd.read_csv(file_path).values
    print(f"Keypoints data shape: {keypoints.shape}")  # Debug: check shape of the data
    print(f"First few keypoints: {keypoints[:5]}")  # Debug: print first few keypoints to inspect
    
    num_keypoints = 33  # Mediapipe provides 33 keypoints
    reshaped_keypoints = keypoints.reshape(-1, num_keypoints, 3)  # Reshape to (num_frames, num_keypoints, 3)
    return reshaped_keypoints

def visualize_keypoints_and_lines(frames_dir1, frames_dir2, keypoints1, keypoints2, output_dir):
    """
    Visualize Mediapipe keypoints and connections for human body visualization.
    """
    os.makedirs(output_dir, exist_ok=True)
    
    frame_files1 = sorted(os.listdir(frames_dir1))
    frame_files2 = sorted(os.listdir(frames_dir2))
    
    num_frames = min(len(frame_files1), len(frame_files2))  # Use the minimum of both frame counts
    
    connections = [
        (0, 1), (1, 2), (2, 3), (3, 7),  # Head to left hand
        (0, 4), (4, 5), (5, 6), (6, 8),  # Head to right hand
        (9, 10), (11, 12),               # Shoulder line
        (11, 13), (13, 15), (15, 17),    # Left arm
        (12, 14), (14, 16), (16, 18),    # Right arm
        (11, 23), (12, 24),              # Torso to legs
        (23, 25), (25, 27), (27, 29), (29, 31),  # Left leg
        (24, 26), (26, 28), (28, 30), (30, 32)   # Right leg
    ]
    
    for i in range(num_frames):
        frame_path1 = os.path.join(frames_dir1, frame_files1[i])
        frame_path2 = os.path.join(frames_dir2, frame_files2[i])
        
        frame1 = cv2.imread(frame_path1)
        frame2 = cv2.imread(frame_path2)
        
        if i >= len(keypoints1) or i >= len(keypoints2):
            continue
        
        # Draw keypoints and connections for video 1
        for kp in keypoints1[i]:
            x, y, _ = kp
            cv2.circle(frame1, (int(x), int(y)), 5, (0, 255, 0), -1)
        for conn in connections:
            x1, y1, _ = keypoints1[i][conn[0]]
            x2, y2, _ = keypoints1[i][conn[1]]
            cv2.line(frame1, (int(x1), int(y1)), (int(x2), int(y2)), (0, 255, 0), 2)
        
        # Draw keypoints and connections for video 2
        for kp in keypoints2[i]:
            x, y, _ = kp
            cv2.circle(frame2, (int(x), int(y)), 5, (0, 0, 255), -1)
        for conn in connections:
            x1, y1, _ = keypoints2[i][conn[0]]
            x2, y2, _ = keypoints2[i][conn[1]]
            cv2.line(frame2, (int(x1), int(y1)), (int(x2), int(y2)), (0, 0, 255), 2)
        
        # Concatenate frames horizontally
        combined_frame = np.hstack((frame1, frame2))
        
        # Save the visualized frame
        output_path = os.path.join(output_dir, f"frame_{i:04d}.jpg")
        cv2.imwrite(output_path, combined_frame)

# Example usage
if __name__ == "__main__":
    keypoints1_path = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/video_1_keypoints.csv'
    keypoints2_path = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/video_2_keypoints.csv'
    frames_dir1 = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/frame_video1'
    frames_dir2 = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/frame_video2'
    output_dir = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/comparision'
    
    keypoints1 = load_keypoints_from_csv(keypoints1_path)
    keypoints2 = load_keypoints_from_csv(keypoints2_path)
    
    visualize_keypoints_and_lines(frames_dir1, frames_dir2, keypoints1, keypoints2, output_dir)


FileNotFoundError: [Errno 2] No such file or directory: '/path_to_video_1_keypoints.csv'

In [21]:
import cv2
import pandas as pd
import os
import numpy as np

# Mediapipe connections for keypoints
BODY_CONNECTIONS = [
    (0, 1), (1, 2), (2, 3), (3, 7),
    (0, 4), (4, 5), (5, 6), (6, 8),
    (9, 10), (11, 12), (11, 13), (13, 15),
    (15, 17), (15, 19), (15, 21), (17, 19),
    (12, 14), (14, 16), (16, 18), (16, 20), (16, 22),
    (23, 24), (23, 25), (24, 26), (25, 27), (26, 28),
    (27, 29), (28, 30), (29, 31), (30, 32)
]

def load_keypoints_from_csv(file_path):
    """Load keypoints from a CSV file."""
    keypoints = pd.read_csv(file_path).values
    num_keypoints = 33
    reshaped_keypoints = keypoints.reshape(-1, num_keypoints, 3)
    return reshaped_keypoints

def draw_body_keypoints(frame, keypoints, connections, color):
    """Draw keypoints and connections on the frame."""
    for i, (x, y, visibility) in enumerate(keypoints):
        if visibility > 0.5:  # Only draw if visibility is high
            cv2.circle(frame, (int(x), int(y)), 5, color, -1)
            cv2.putText(frame, str(i), (int(x), int(y) - 10),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.4, color, 1, cv2.LINE_AA)
    for (start, end) in connections:
        x1, y1, v1 = keypoints[start]
        x2, y2, v2 = keypoints[end]
        if v1 > 0.5 and v2 > 0.5:
            cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), color, 2)

def visualize_keypoints_and_lines(frames_dir1, frames_dir2, keypoints1, keypoints2, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    frame_files1 = sorted(os.listdir(frames_dir1))
    frame_files2 = sorted(os.listdir(frames_dir2))
    
    for i in range(min(len(frame_files1), len(frame_files2))):
        frame_path1 = os.path.join(frames_dir1, frame_files1[i])
        frame_path2 = os.path.join(frames_dir2, frame_files2[i])
        
        frame1 = cv2.imread(frame_path1)
        frame2 = cv2.imread(frame_path2)
        
        if i >= len(keypoints1) or i >= len(keypoints2):
            continue
        
        draw_body_keypoints(frame1, keypoints1[i], BODY_CONNECTIONS, (0, 255, 0))  # Green for video 1
        draw_body_keypoints(frame2, keypoints2[i], BODY_CONNECTIONS, (0, 0, 255))  # Red for video 2
        
        combined_frame = np.hstack((frame1, frame2))
        output_path = os.path.join(output_dir, f"frame_{i:04d}.jpg")
        cv2.imwrite(output_path, combined_frame)
        print(f"Saved frame {i} at {output_path}")  # Debugging frame save

# Example usage
if __name__ == "__main__":
    keypoints1_path = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/video_1_keypoints.csv'
    keypoints2_path = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/video_2_keypoints.csv'
    frames_dir1 = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/frame_video1'
    frames_dir2 = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/frame_video2'
    output_dir = '/home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/comparision'
    
    
    keypoints1 = load_keypoints_from_csv(keypoints1_path)
    keypoints2 = load_keypoints_from_csv(keypoints2_path)
    
    visualize_keypoints_and_lines(frames_dir1, frames_dir2, keypoints1, keypoints2, output_dir)


Saved frame 0 at /home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/comparision/frame_0000.jpg
Saved frame 1 at /home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/comparision/frame_0001.jpg
Saved frame 2 at /home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/comparision/frame_0002.jpg
Saved frame 3 at /home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/comparision/frame_0003.jpg
Saved frame 4 at /home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/comparision/frame_0004.jpg
Saved frame 5 at /home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/comparision/frame_0005.jpg
Saved frame 6 at /home/pratyush/Documents/Internship assesment/aadiyog internship assesment/data/frames/comparision/frame_0006.jpg
Saved frame 7 at /home/pratyush/Documents/Internship assesment/aadiyog internship a